name: Deploy Application

on:
  push:
    branches:
      - main
      - develop
      - feature/*
    paths:
      - 'app/**'
      - '.github/workflows/app_deploy.yml'
  pull_request:
    branches:
      - main
      - develop
      - feature/*
    paths:
      - 'app/**'
      - '.github/workflows/app_deploy.yml'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./app

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch || github.ref }}

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build --prefix . || (cat npm-debug.log && exit 1)

    - name: List build directory
      run: ls -la ./build

    - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GH_TOKEN }}
        action: 'upload'
        app_location: '' # Current working directory is already app
        api_location: '' # Leave empty if you don't have an API
        output_location: 'build' # The directory from which to deploy
