name: Deploy Application

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'tf/**'

  pull_request:
    branches:
      - '**'
    paths-ignore:
      - 'tf/**' 

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build || (cat npm-debug.log && exit 1)

    - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GH_TOKEN }}
        action: 'upload'
        app_location: '/' # Root of your project
        api_location: '' # Leave empty if you don't have an API
        output_location: 'build' # The directory from which to deploy
